TRUNCATE TABLE `users`;
INSERT INTO `users` (`name`, `email`, `birthdate`, `confirmed`, `favorite_number`) VALUES ('Juhász Patrik PhD', 'dobos.nikoletta@antal.com', '2002-08-07', 1, 2);
INSERT INTO `users` (`name`, `email`, `birthdate`, `confirmed`, `favorite_number`) VALUES ('ifj. Sipos Patrik', 'onovak@yahoo.com', '1973-12-18', 0, 1);
INSERT INTO `users` (`name`, `email`, `birthdate`, `confirmed`, `favorite_number`) VALUES ('Jakab Kornélné', 'psandor@gmail.com', '1989-05-12', 1, 5);
INSERT INTO `users` (`name`, `email`, `birthdate`, `confirmed`, `favorite_number`) VALUES ('Vincze Mátyás PhD', 'linda83@simon.net', '1983-07-23', 1, 6);
INSERT INTO `users` (`name`, `email`, `birthdate`, `confirmed`, `favorite_number`) VALUES ('ifj. Vörös Marietta', 'pvass@yahoo.com', '1971-04-05', 1, 6);
INSERT INTO `users` (`name`, `email`, `birthdate`, `confirmed`, `favorite_number`) VALUES ('id. Lukács Milán', 'kvass@hotmail.com', '2004-09-17', 0, 9);
INSERT INTO `users` (`name`, `email`, `birthdate`, `confirmed`, `favorite_number`) VALUES ('Dr. Veres Georgina PhD', 'kevin64@farago.com', '1992-03-02', 0, 7);
INSERT INTO `users` (`name`, `email`, `birthdate`, `confirmed`, `favorite_number`) VALUES ('Dr. Végh Szervácné', 'liliana.vass@pap.com', '1994-11-06', 0, 6);
INSERT INTO `users` (`name`, `email`, `birthdate`, `confirmed`, `favorite_number`) VALUES ('Lakatos Erzsébet', 'zeteny84@kiraly.com', '1989-04-14', 1, 2);
INSERT INTO `users` (`name`, `email`, `birthdate`, `confirmed`, `favorite_number`) VALUES ('Gáspár Liliána', 'rhegedus@yahoo.com', '1992-08-20', 1, 8);
INSERT INTO `users` (`name`, `email`, `birthdate`, `confirmed`, `favorite_number`) VALUES ('id. Major László', 'gitta94@yahoo.com', '1989-04-09', 0, 6);
INSERT INTO `users` (`name`, `email`, `birthdate`, `confirmed`, `favorite_number`) VALUES ('Király Mihályné', 'valeria.jakab@pinter.info', '1974-06-04', 0, 5);
INSERT INTO `users` (`name`, `email`, `birthdate`, `confirmed`, `favorite_number`) VALUES ('Dr. Pál Rudolf PhD', 'judit.torok@hotmail.com', '1972-05-14', 0, 10);
INSERT INTO `users` (`name`, `email`, `birthdate`, `confirmed`, `favorite_number`) VALUES ('ifj. Juhász Zoltán', 'armin50@nemeth.net', '2007-07-15', 0, 1);
INSERT INTO `users` (`name`, `email`, `birthdate`, `confirmed`, `favorite_number`) VALUES ('Tóth Flóra PhD', 'magyar.erno@meszaros.org', '1992-09-05', 0, 10);
INSERT INTO `users` (`name`, `email`, `birthdate`, `confirmed`, `favorite_number`) VALUES ('Balog Rudolf', 'racz.benedek@gmail.com', '1973-03-20', 0, 4);
INSERT INTO `users` (`name`, `email`, `birthdate`, `confirmed`, `favorite_number`) VALUES ('ifj. Tamás Gitta', 'jakab.klaudia@gal.com', '1985-02-16', 1, 4);
INSERT INTO `users` (`name`, `email`, `birthdate`, `confirmed`, `favorite_number`) VALUES ('Sipos Panna', 'virag.hegedus@kiss.org', '1981-10-25', 0, 9);
INSERT INTO `users` (`name`, `email`, `birthdate`, `confirmed`, `favorite_number`) VALUES ('Gál Endrené', 'jbudai@orban.com', '1998-03-03', 0, 4);
INSERT INTO `users` (`name`, `email`, `birthdate`, `confirmed`, `favorite_number`) VALUES ('Faragó Evelin PhD', 'mira08@lukacs.net', '1991-06-13', 1, 4);
INSERT INTO `users` (`name`, `email`, `birthdate`, `confirmed`, `favorite_number`) VALUES ('Molnár Mihály', 'aorsos@gmail.com', '1983-12-05', 0, 3);
INSERT INTO `users` (`name`, `email`, `birthdate`, `confirmed`, `favorite_number`) VALUES ('Dr. Papp Jenőné', 'kiraly.henrietta@balogh.com', '1987-08-24', 0, 7);
INSERT INTO `users` (`name`, `email`, `birthdate`, `confirmed`, `favorite_number`) VALUES ('Prof. Hegedűs Botondné', 'kristof86@hotmail.com', '2001-09-09', 1, 8);
INSERT INTO `users` (`name`, `email`, `birthdate`, `confirmed`, `favorite_number`) VALUES ('Gulyás Zoltán', 'sandor49@szekely.com', '1984-11-30', 1, 2);
INSERT INTO `users` (`name`, `email`, `birthdate`, `confirmed`, `favorite_number`) VALUES ('Balog Ottó PhD', 'soma.kiss@gmail.com', '1980-01-14', 1, 2);
INSERT INTO `users` (`name`, `email`, `birthdate`, `confirmed`, `favorite_number`) VALUES ('Dr. Kis Alexa PhD', 'zita.meszaros@gmail.com', '2012-07-07', 1, 7);
INSERT INTO `users` (`name`, `email`, `birthdate`, `confirmed`, `favorite_number`) VALUES ('Bálint Míra PhD', 'kristof84@hotmail.com', '1978-01-17', 0, 2);
INSERT INTO `users` (`name`, `email`, `birthdate`, `confirmed`, `favorite_number`) VALUES ('Molnár Árpádné', 'kornel.kozma@nagy.com', '2001-09-28', 1, 9);
INSERT INTO `users` (`name`, `email`, `birthdate`, `confirmed`, `favorite_number`) VALUES ('Prof. Hajdu Gitta PhD', 'csonka.antal@kiraly.info', '1995-01-06', 1, 10);
INSERT INTO `users` (`name`, `email`, `birthdate`, `confirmed`, `favorite_number`) VALUES ('Antal Zsombor PhD', 'barnabas98@gmail.com', '2003-11-23', 1, 8);
INSERT INTO `users` (`name`, `email`, `birthdate`, `confirmed`, `favorite_number`) VALUES ('ifj. Dudás Árminné', 'richard.kocsis@molnar.info', '1976-12-08', 1, 7);
INSERT INTO `users` (`name`, `email`, `birthdate`, `confirmed`, `favorite_number`) VALUES ('Prof. Balog Gizella PhD', 'phalasz@gmail.com', '2009-10-12', 1, 4);
INSERT INTO `users` (`name`, `email`, `birthdate`, `confirmed`, `favorite_number`) VALUES ('Török Árpád PhD', 'ulakatos@toth.com', '1998-04-02', 0, 10);
INSERT INTO `users` (`name`, `email`, `birthdate`, `confirmed`, `favorite_number`) VALUES ('Nagy Ottóné', 'zfeher@gmail.com', '1988-03-30', 0, 5);
INSERT INTO `users` (`name`, `email`, `birthdate`, `confirmed`, `favorite_number`) VALUES ('ifj. Orosz János', 'zsolt.kiraly@gmail.com', '2004-04-26', 0, 8);
INSERT INTO `users` (`name`, `email`, `birthdate`, `confirmed`, `favorite_number`) VALUES ('Juhász Zsombor PhD', 'arpad.pal@novak.com', '1972-09-23', 0, 2);
INSERT INTO `users` (`name`, `email`, `birthdate`, `confirmed`, `favorite_number`) VALUES ('Szalai Zétény', 'fszekeres@yahoo.com', '2001-06-15', 0, 5);
INSERT INTO `users` (`name`, `email`, `birthdate`, `confirmed`, `favorite_number`) VALUES ('Dr. Orsós Léna', 'katinka39@yahoo.com', '1985-12-29', 1, 9);
INSERT INTO `users` (`name`, `email`, `birthdate`, `confirmed`, `favorite_number`) VALUES ('id. Tamás Antal PhD', 'gabor.balazs@meszaros.com', '2000-01-06', 0, 5);
INSERT INTO `users` (`name`, `email`, `birthdate`, `confirmed`, `favorite_number`) VALUES ('ifj. Papp Sándor PhD', 'arpad.bakos@bakos.org', '1983-01-30', 1, 1);
INSERT INTO `users` (`name`, `email`, `birthdate`, `confirmed`, `favorite_number`) VALUES ('Gulyás Árpád PhD', 'ddudas@yahoo.com', '2014-10-11', 0, 7);
INSERT INTO `users` (`name`, `email`, `birthdate`, `confirmed`, `favorite_number`) VALUES ('Nagy Gézané', 'tlengyel@halasz.com', '2008-03-07', 1, 7);
INSERT INTO `users` (`name`, `email`, `birthdate`, `confirmed`, `favorite_number`) VALUES ('Antal Liza PhD', 'fpal@yahoo.com', '1984-01-16', 1, 9);
INSERT INTO `users` (`name`, `email`, `birthdate`, `confirmed`, `favorite_number`) VALUES ('Tóth Vince PhD', 'vnovak@hotmail.com', '1974-03-02', 0, 5);
INSERT INTO `users` (`name`, `email`, `birthdate`, `confirmed`, `favorite_number`) VALUES ('ifj. Bakos Barnabás PhD', 'qhalasz@kiraly.net', '1990-05-29', 0, 6);
INSERT INTO `users` (`name`, `email`, `birthdate`, `confirmed`, `favorite_number`) VALUES ('Dr. Nagy Soma', 'flora70@tamas.biz', '1976-01-08', 0, 1);
INSERT INTO `users` (`name`, `email`, `birthdate`, `confirmed`, `favorite_number`) VALUES ('Kis Fanni', 'knemes@soos.net', '1979-12-02', 0, 5);
INSERT INTO `users` (`name`, `email`, `birthdate`, `confirmed`, `favorite_number`) VALUES ('Bakos Henrietta PhD', 'hegedus.bence@varadi.com', '1974-12-01', 1, 2);
INSERT INTO `users` (`name`, `email`, `birthdate`, `confirmed`, `favorite_number`) VALUES ('ifj. Deák Jánosné', 'uhegedus@orosz.com', '1986-08-29', 0, 4);
INSERT INTO `users` (`name`, `email`, `birthdate`, `confirmed`, `favorite_number`) VALUES ('id. Lukács Sára PhD', 'bence07@pinter.com', '1984-02-24', 1, 9);
